# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'Firebase', '>=2.5.1'

target 'lab8' do

end

target 'lab8Tests' do

end

target 'lab8UITests' do

end

